language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-prod.txt
  - pip install coverage
before_script:
  - ./start_ci_db.bash
  - cd wellregistry
  - cp .env.sample .env
script:
  - coverage run --source='.' manage.py test
after_failure:
  - bash docker logs registry_postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash docker rm -f registry_postgres
