language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - cd wellregistry
script:
  - coverage run --source='.' manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
