"""
# Generated by Django 3.0.5 on 2020-05-01 16:33
migration: initial registry ORM
"""
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Django Migration.

    initial registry ORM.

    """
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_cd', models.CharField(max_length=20)),
                ('well_depth_units', models.IntegerField()),
                ('alt_datum_cd', models.CharField(max_length=10)),
                ('alt_units', models.IntegerField()),
                ('horz_datum', models.CharField(max_length=10)),
                ('nat_aquifer_cd', models.CharField(max_length=10)),
                ('country_cd', models.CharField(max_length=2)),
                ('state_cd', models.CharField(max_length=2)),
                ('county_cd', models.CharField(max_length=3)),
                ('agency_nm', models.CharField(max_length=200)),
                ('agency_med', models.CharField(max_length=200)),
                ('site_no', models.CharField(max_length=16)),
                ('site_name', models.CharField(max_length=300)),
                ('dec_lat_va', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dec_long_va', models.DecimalField(decimal_places=8, max_digits=11)),
                ('alt_va', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nat_aqfr_desc', models.CharField(max_length=100)),
                ('local_aquifer_name', models.CharField(max_length=100)),
                ('qw_sn_flag', models.IntegerField(default=0, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('qw_baseline_flag', models.IntegerField(default=0, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('qw_well_chars', models.CharField(max_length=3)),
                ('qw_well_purpose', models.CharField(max_length=15)),
                ('wl_sn_flag', models.IntegerField(default=0, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('wl_baseline_flag', models.IntegerField(default=0, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('wl_well_chars', models.CharField(max_length=3)),
                ('wl_well_purpose', models.CharField(max_length=15)),
                ('data_provider', models.CharField(max_length=30)),
                ('qw_sys_name', models.CharField(max_length=50)),
                ('wl_sys_name', models.CharField(max_length=50)),
                ('pk_siteid', models.CharField(max_length=37)),
                ('display_flag', models.IntegerField(default=0, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('wl_data_provider', models.CharField(max_length=20)),
                ('qw_data_provider', models.CharField(max_length=20)),
                ('lith_data_provider', models.CharField(max_length=20)),
                ('const_data_provider', models.CharField(max_length=20)),
                ('well_depth', models.DecimalField(decimal_places=8, max_digits=11)),
                ('link', models.CharField(max_length=500)),
                ('wl_well_purpose_notes', models.CharField(max_length=4000)),
                ('qw_well_purpose_notes', models.CharField(max_length=4000)),
                ('insert_user_id', models.CharField(max_length=50)),
                ('update_user_id', models.CharField(max_length=50)),
                ('wl_well_type', models.CharField(max_length=3)),
                ('qw_well_type', models.CharField(max_length=3)),
                ('local_aquifer_cd', models.CharField(max_length=20)),
                ('review_flag', models.CharField(max_length=1)),
                ('site_type', models.CharField(max_length=10)),
                ('aqfr_char', models.CharField(max_length=10)),
                ('horz_method', models.CharField(max_length=300)),
                ('horz_acy', models.CharField(max_length=300)),
                ('alt_method', models.CharField(max_length=300)),
                ('alt_acy', models.CharField(max_length=300)),
                ('insert_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
