"""
Changes to make well_depth and well_depth_unit required fields in MonitoringLoccation
"""
# Generated by Django 3.1.2 on 2020-10-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Auto generated migration
    """

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlocation',
            name='well_depth',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='well_depth_units',
            field=models.ForeignKey(db_column='well_depth_units', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.unitslookup', to_field='unit_id'),
        ),
    ]
