# Generated by Django 3.0.5 on 2020-05-01 16:33

from django.db import migrations, models
from wellregistry.wellregistry.env import Env


class Migration(migrations.Migration):

    initial = False

    dependencies = [('migrations', '0001_initial')]

    env = Env()

    operations = [
        # grant CRUD to app user -- after 0001_initial, this cannot be granted until the tables is created
        migrations.RunSQL(
            sql=f"""
                GRANT INSERT, SELECT, UPDATE, DELETE
                ON {env.APP_SCHEMA}.registry
                TO {env.APP_CLIENT_USERNAME}
            """,
            reverse_sql=f"""
                REVOKE INSERT, SELECT, UPDATE, DELETE
                ON {env.APP_SCHEMA}.registry
                FROM {env.APP_CLIENT_USERNAME}
            """),
    ]
