# Generated by Django 3.0.6 on 2020-06-03 17:57

from django.db import migrations

AGENCIES = [
    u'usgs',
    u'adwr',
    u'mbmg'
]

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    add_p = Permission.objects.get(codename=u'add_registry')
    change_p = Permission.objects.get(codename=u'change_registry')
    delete_p = Permission.objects.get(codename=u'delete_registry')

    existing_agencies = Group.objects.all().values_list('name', flat=True)
    for agency in AGENCIES:
        if agency not in existing_agencies:
            group = Group.objects.create(name=agency)
            group.permissions.set([add_p, change_p, delete_p])
            group.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=AGENCIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_registry_table'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
