# Generated by Django 3.0.6 on 2020-06-03 17:57

from django.db import migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    nwis_group = Group.objects.create(name=u'nwis')
    add_p = Permission.objects.get(codename=u'add_registry')
    change_p = Permission.objects.get(codename=u'change_registry')
    delete_p = Permission.objects.get(codename=u'delete_registry')
    nwis_group.permissions.set([add_p, change_p, delete_p])
    nwis_group.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'nwis'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_registry_table'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration),
    ]
