# Generated by Django 3.0.7 on 2020-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_add_agency_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
    ]
