"""
Changes to implement arbitrary decimal field
"""
# Generated by Django 3.1.2 on 2020-11-03 14:20

from django.db import migrations
import registry.models


class Migration(migrations.Migration):
    """
    Migration for DecimalFields to ArbiraryDecimalFields
    """

    dependencies = [
        ('registry', '0002_well_depth_and_unit_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlocation',
            name='alt_va',
            field=registry.models.ArbitraryDecimalFields(null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='dec_lat_va',
            field=registry.models.ArbitraryDecimalFields(null=True, verbose_name='Latitude(decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='dec_long_va',
            field=registry.models.ArbitraryDecimalFields(null=True, verbose_name='Longitude(decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='well_depth',
            field=registry.models.ArbitraryDecimalFields(null=True),
        ),
    ]
