# Generated by Django 3.0.7 on 2020-06-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_country_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyLovLookup',
            fields=[
                ('agency_cd', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agency_nm', models.CharField(blank=True, max_length=150, null=True)),
                ('org_type', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_med', models.CharField(blank=True, max_length=200, null=True)),
                ('state_cd', models.CharField(blank=True, max_length=5, null=True)),
                ('agency_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'agency_lov',
            },
        ),
        migrations.CreateModel(
            name='AltDatumDimLookup',
            fields=[
                ('adatum_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adatum_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('datum_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'alt_datum_dim',
            },
        ),
        migrations.CreateModel(
            name='HorzDatumDimLookup',
            fields=[
                ('hdatum_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hdatum_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'horz_datum_dim',
            },
        ),
        migrations.CreateModel(
            name='NatAqfrLookup',
            fields=[
                ('nat_aqfr_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nat_aqfr_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nat_aqfr',
            },
        ),
        migrations.CreateModel(
            name='UnitsDimLookup',
            fields=[
                ('unit_id', models.FloatField(primary_key=True, serialize=False)),
                ('unit_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_abrev', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'units_dim',
            },
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='country_cd',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='country_nm',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='registry',
            name='country_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.CountryLookup'),
        ),
        migrations.AlterModelTable(
            name='countrylookup',
            table='country',
        ),
        migrations.CreateModel(
            name='StateLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_cd', models.CharField(max_length=2)),
                ('state_nm', models.CharField(max_length=53)),
                ('state_post_cd', models.CharField(max_length=2)),
                ('state_max_lat_va', models.CharField(blank=True, max_length=11, null=True)),
                ('state_min_lat_va', models.CharField(blank=True, max_length=11, null=True)),
                ('state_max_long_va', models.CharField(blank=True, max_length=12, null=True)),
                ('state_min_long_va', models.CharField(blank=True, max_length=12, null=True)),
                ('state_max_alt_va', models.CharField(blank=True, max_length=8, null=True)),
                ('state_min_alt_va', models.CharField(blank=True, max_length=8, null=True)),
                ('state_md', models.CharField(max_length=8)),
                ('country_cd', models.ForeignKey(db_column='country_cd', on_delete=django.db.models.deletion.DO_NOTHING, to='registry.CountryLookup')),
            ],
            options={
                'db_table': 'state',
                'unique_together': {('country_cd', 'state_cd')},
            },
        ),
        migrations.CreateModel(
            name='CountyLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_cd', models.CharField(max_length=3)),
                ('county_nm', models.CharField(max_length=48)),
                ('county_max_lat_va', models.CharField(max_length=11)),
                ('county_min_lat_va', models.CharField(max_length=11)),
                ('county_max_long_va', models.CharField(max_length=12)),
                ('county_min_long_va', models.CharField(max_length=12)),
                ('county_max_alt_va', models.CharField(max_length=8)),
                ('county_min_alt_va', models.CharField(max_length=8)),
                ('county_md', models.CharField(max_length=8)),
                ('country_cd', models.ForeignKey(db_column='country_cd', on_delete=django.db.models.deletion.DO_NOTHING, to='registry.CountryLookup')),
                ('state_cd', models.ForeignKey(db_column='state_cd', on_delete=django.db.models.deletion.DO_NOTHING, to='registry.StateLookup')),
            ],
            options={
                'db_table': 'county',
                'unique_together': {('country_cd', 'state_cd', 'county_cd')},
            },
        ),
        migrations.AlterField(
            model_name='registry',
            name='agency_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.AgencyLovLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='alt_datum_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.AltDatumDimLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='alt_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.UnitsDimLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='county_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.CountyLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='horz_datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.HorzDatumDimLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='nat_aquifer_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.NatAqfrLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='state_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.StateLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='well_depth_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.UnitsDimLookup'),
        ),
    ]
