# The below suppresses pylint message: Module name "0004_lookup_tables" doesn't conform to snake_case naming style
# pylint: disable-msg=C0103
# Enable check for the rest of the file
# pylint: enable-msg=C0103
"""
# Data migration to create the lookup tables.
"""
# Generated by Django 3.0.7 on 2020-07-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Defines the migrations for creating look up tables.

    """

    dependencies = [
        ('registry', '0003_country_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_cd', models.CharField(max_length=50, unique=True)),
                ('agency_nm', models.CharField(blank=True, max_length=150, null=True)),
                ('agency_med', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='AltitudeDatumLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adatum_cd', models.CharField(max_length=10, unique=True)),
                ('adatum_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'altitude_datum',
            },
        ),
        migrations.CreateModel(
            name='HorizontalDatumLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdatum_cd', models.CharField(max_length=10, unique=True)),
                ('hdatum_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'horizontal_datum',
            },
        ),
        migrations.CreateModel(
            name='NatAqfrLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_aqfr_cd', models.CharField(max_length=10, unique=True)),
                ('nat_aqfr_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nat_aqfr',
            },
        ),
        migrations.CreateModel(
            name='UnitsLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_desc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.RemoveField(
            model_name='registry',
            name='agency_cd',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='alt_datum_cd',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='alt_units',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='country_cd',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='county_cd',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='horz_datum',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='nat_aquifer_cd',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='state_cd',
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='country_cd',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='countrylookup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='registry',
            name='country',
            field=models.ForeignKey(db_column='country_cd', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.CountryLookup', to_field='country_cd'),
        ),
        migrations.AlterField(
            model_name='countrylookup',
            name='country_nm',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterModelTable(
            name='countrylookup',
            table='country',
        ),
        migrations.CreateModel(
            name='StateLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_cd', models.CharField(max_length=2)),
                ('state_nm', models.CharField(max_length=53)),
                ('country_cd', models.ForeignKey(db_column='country_cd', on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='registry.CountryLookup')),
            ],
            options={
                'db_table': 'state',
                'unique_together': {('country_cd', 'state_cd')},
            },
        ),
        migrations.CreateModel(
            name='CountyLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_cd', models.CharField(max_length=3)),
                ('county_nm', models.CharField(max_length=48)),
                ('country_cd', models.ForeignKey(db_column='country_cd', on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='registry.CountryLookup')),
                ('state_cd', models.ForeignKey(db_column='state_cd', on_delete=django.db.models.deletion.DO_NOTHING,
                                               to='registry.StateLookup')),
            ],
            options={
                'db_table': 'county',
                'unique_together': {('country_cd', 'state_cd', 'county_cd')},
            },
        ),
        migrations.AddField(
            model_name='registry',
            name='agency',
            field=models.ForeignKey(db_column='agency_cd', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.AgencyLookup', to_field='agency_cd'),
        ),
        migrations.AddField(
            model_name='registry',
            name='altitude_datum',
            field=models.ForeignKey(db_column='altitude_datum_cd', default=0, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='registry.AltitudeDatumLookup',
                                    to_field='adatum_cd'),
        ),
        migrations.AddField(
            model_name='registry',
            name='altitude_units',
            field=models.ForeignKey(db_column='altitude_units', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.UnitsLookup'),
        ),
        migrations.AddField(
            model_name='registry',
            name='county',
            field=models.ForeignKey(db_column='county_id', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.CountyLookup'),
        ),
        migrations.AddField(
            model_name='registry',
            name='horizontal_datum',
            field=models.ForeignKey(db_column='horizontal_datum_cd', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='registry.HorizontalDatumLookup',
                                    to_field='hdatum_cd'),
        ),
        migrations.AddField(
            model_name='registry',
            name='nat_aqfr',
            field=models.ForeignKey(db_column='nat_aqfr_cd', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.NatAqfrLookup', to_field='nat_aqfr_cd'),
        ),
        migrations.AddField(
            model_name='registry',
            name='state',
            field=models.ForeignKey(db_column='state_id', null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='registry.StateLookup'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='well_depth_units',
            field=models.ForeignKey(db_column='well_depth_units', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='registry.UnitsLookup'),
        ),
    ]
