# The below suppresses pylint message: Module name "*" doesn't conform to snake_case naming style
# pylint: disable-msg=C0103
# Enable check for the rest of the file
# pylint: enable-msg=C0103
"""
# Changes to the Registry model
"""
# Generated by Django 3.1 on 2020-08-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Defines the migrations for updating the Registry model.
    """
    dependencies = [
        ('registry', '0008_populate_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='alt_acy',
            field=models.CharField(blank=True, max_length=300, verbose_name='Altitude accuracy'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='alt_method',
            field=models.CharField(blank=True, max_length=300, verbose_name='Altitude method'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='aqfr_type',
            field=models.CharField(blank=True, choices=[('CONFINED', 'Confined'), ('UNCONFINED', 'Unconfined')], db_column='aqfr_char', max_length=10, verbose_name='Aquifer type'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='horz_acy',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lat/Long accuracy'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='horz_method',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lat/Long method'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='nat_aqfr',
            field=models.ForeignKey(blank=True, db_column='nat_aqfr_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.nataqfrlookup', to_field='nat_aqfr_cd', verbose_name='National aquifer'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_baseline_flag',
            field=models.BooleanField(default=False, verbose_name='QW baseline?'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_network_name',
            field=models.CharField(blank=True, db_column='qw_sys_name', max_length=50, verbose_name='QW network name'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_sn_flag',
            field=models.BooleanField(default=False, verbose_name='In QW sub-network?'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_well_chars',
            field=models.CharField(blank=True, choices=[('1', 'Background'), ('2', 'Suspected/Anticipated Changes'), ('3', 'Known Changes')], max_length=3, verbose_name='QW well characteristics'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_well_purpose',
            field=models.CharField(blank=True, choices=[('1', 'Dedicated Monitoring/Observation'), ('2', 'Other')], max_length=15, verbose_name='QW well purpose'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_well_purpose_notes',
            field=models.CharField(blank=True, max_length=4000, verbose_name='QW well purpose notes'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='qw_well_type',
            field=models.CharField(blank=True, choices=[('1', 'Surveillance'), ('2', 'Trend'), ('3', 'Special')], max_length=3, verbose_name='QW well type'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_baseline_flag',
            field=models.BooleanField(default=False, verbose_name='WL baseline?'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_network_name',
            field=models.CharField(blank=True, db_column='wl_sys_name', max_length=50, verbose_name='WL network name'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_sn_flag',
            field=models.BooleanField(default=False, verbose_name='In WL sub-network?'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_well_chars',
            field=models.CharField(blank=True, choices=[('1', 'Background'), ('2', 'Suspected/Anticipated Changes'), ('3', 'Known Changes')], max_length=3, verbose_name='WL well characteristics'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_well_purpose',
            field=models.CharField(blank=True, choices=[('1', 'Dedicated Monitoring/Observation'), ('2', 'Other')], max_length=15, verbose_name='WL well purpose'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_well_purpose_notes',
            field=models.CharField(blank=True, max_length=4000, verbose_name='WL well purpose notes'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='wl_well_type',
            field=models.CharField(blank=True, choices=[('1', 'Surveillance'), ('2', 'Trend'), ('3', 'Special')], max_length=3, verbose_name='WL well type'),
        ),
    ]
