# Generated by Django 3.1 on 2020-08-27 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0010_registry_updates_20200824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registry',
            new_name='MonitoringLocation',
        ),
    ]
