# The below suppresses pylint message: Module name "*" doesn't conform to snake_case naming style
# pylint: disable-msg=C0103
# Enable check for the rest of the file
# pylint: enable-msg=C0103
"""
# Changes to the Registry model
"""
# Generated by Django 3.1 on 2020-08-27 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """
    Changes the name of registry_registry table to registry_monitoringlocation
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0010_registry_updates_20200824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registry',
            new_name='MonitoringLocation',
        ),
    ]
