# The below suppresses pylint message: Module name "*" doesn't conform to snake_case naming style
# pylint: disable-msg=C0103
# Enable check for the rest of the file
# pylint: enable-msg=C0103
"""
# Changes to the Registry model
"""
# Generated by Django 3.1 on 2020-08-27 21:24

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    """
    Changes on field ordering.
    """

    dependencies = [
        ('registry', '0011_rename_registry_to_monitoring_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencylookup',
            options={'ordering': ['agency_nm']},
        ),
        migrations.AlterModelOptions(
            name='altitudedatumlookup',
            options={'ordering': ['adatum_cd']},
        ),
        migrations.AlterModelOptions(
            name='countrylookup',
            options={'ordering': ['country_nm']},
        ),
        migrations.AlterModelOptions(
            name='countylookup',
            options={'ordering': ['county_nm']},
        ),
        migrations.AlterModelOptions(
            name='horizontaldatumlookup',
            options={'ordering': ['hdatum_cd']},
        ),
        migrations.AlterModelOptions(
            name='nataqfrlookup',
            options={'ordering': ['nat_aqfr_desc']},
        ),
        migrations.AlterModelOptions(
            name='statelookup',
            options={'ordering': ['state_nm']},
        ),
        migrations.AlterModelOptions(
            name='unitslookup',
            options={'ordering': ['unit_desc']},
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state_id', db_column='county_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.countylookup'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country_cd', db_column='state_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.statelookup'),
        ),
    ]
