# The below suppresses pylint message: Module name "*" doesn't conform to snake_case naming style
# pylint: disable-msg=C0103
# Enable check for the rest of the file
# pylint: enable-msg=C0103
"""
# Updating fields including well depth which did not allow for well depths over 100)
"""
# Generated by Django 3.1 on 2020-09-16 19:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    """
    Changes to fields
    """

    dependencies = [
        ('registry', '0012_registry_lookup_ordering_and_chaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlocation',
            name='alt_va',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='altitude_datum',
            field=models.ForeignKey(db_column='altitude_datum_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.altitudedatumlookup', to_field='adatum_cd'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='altitude_units',
            field=models.ForeignKey(db_column='altitude_units', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.unitslookup', to_field='unit_id'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state_id', db_column='county_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.countylookup'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='dec_lat_va',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Latitude(decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='dec_long_va',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='Longitude(decimal degrees)'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='horizontal_datum',
            field=models.ForeignKey(db_column='horizontal_datum_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.horizontaldatumlookup', to_field='hdatum_cd'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='nat_aqfr',
            field=models.ForeignKey(db_column='nat_aqfr_cd', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.nataqfrlookup', to_field='nat_aqfr_cd', verbose_name='National aquifer'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='site_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='site_type',
            field=models.CharField(choices=[('WELL', 'Well'), ('SPRING', 'Spring')], max_length=10),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country_cd', db_column='state_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.statelookup'),
        ),
        migrations.AlterField(
            model_name='monitoringlocation',
            name='well_depth',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
    ]
